- name: Add apt repository for certbot
  apt_repository:
    repo: 'ppa:certbot/certbot'
    codename: trusty

- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install apt packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - python-certbot-nginx
    - vim
    - curl

- name: Upgrade apt packages
  apt:
    upgrade: safe

- name: Reboot the server to avoid issues with iptables setup.
  run_once: true
  reboot:
